pipeline:
    name: Example
    identifier: Example
    projectIdentifier: VikasNgGitSync4
    orgIdentifier: testpiyush
    tags: {}
    stages:
        - stage:
              name: helloworld
              identifier: helloworld
              type: CI
              spec:
                  cloneCodebase: false
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: example
                                identifier: example
                                spec:
                                    connectorRef: <+input>
                                    image: <+input>
                                    command: echo "hello world"
                                    privileged: false
                  serviceDependencies: []
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: <+input>
                          namespace: default
        - stage:
              name: testName
              identifier: testName
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: <+input>
                          namespace: <+input>
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: ArtifactoryUpload
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: testC
                                    target: <+input>
                                    sourcePath: <+input>
                                failureStrategies: []
    properties:
        ci:
            codebase:
                connectorRef: gitConnector
                build: <+input>
